"""renombrar metadata a datos en notificacion

Revision ID: 26c7b5276ac9
Revises: 34fc1a59ab79
Create Date: 2026-09-21 20:32:11.823900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26c7b5276ac9'
down_revision: Union[str, Sequence[str], None] = '34fc1a59ab79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
