"""crear tabla notificacion

Revision ID: 34fc1a59ab79
Revises: fa7535768ec2
Create Date: 2026-09-21 20:31:08.844363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34fc1a59ab79'
down_revision: Union[str, Sequence[str], None] = 'fa7535768ec2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_caja_turno_abierto_caja'), table_name='caja_turno', postgresql_where="((estado)::text = 'abierto'::text)")
    op.drop_index(op.f('uq_caja_turno_abierto_usuario'), table_name='caja_turno', postgresql_where="((estado)::text = 'abierto'::text)")
    op.drop_index(op.f('ix_cita_empleado'), table_name='cita')
    op.drop_index(op.f('ix_cita_sucursal'), table_name='cita')
    op.drop_index(op.f('ix_detalle_venta_cita'), table_name='detalle_venta')
    op.drop_index(op.f('ix_devolucion_turno'), table_name='devolucion')
    op.drop_index(op.f('ix_devolucion_venta'), table_name='devolucion')
    op.create_index(op.f('ix_devolucion_venta_id'), 'devolucion', ['venta_id'], unique=False)
    op.drop_index(op.f('ix_devolucion_linea_devolucion'), table_name='devolucion_linea')
    op.drop_index(op.f('ix_devolucion_prov_proveedor'), table_name='devolucion_proveedor')
    op.drop_index(op.f('ix_devolucion_prov_recepcion'), table_name='devolucion_proveedor')
    op.drop_index(op.f('ix_devolucion_prov_detalle_devolucion'), table_name='devolucion_proveedor_detalle')
    op.drop_index(op.f('ix_devolucion_prov_detalle_recepcion_detalle'), table_name='devolucion_proveedor_detalle')
    op.drop_index(op.f('ix_movimiento_instancia_abierta'), table_name='movimiento_inventario')
    op.drop_index(op.f('ix_pedido_proveedor_proveedor'), table_name='pedido_proveedor')
    op.drop_index(op.f('ix_pedido_proveedor_sucursal'), table_name='pedido_proveedor')
    op.drop_constraint(op.f('ck_pedido_proveedor_estado'), 'pedido_proveedor', type_='check')
    op.drop_index(op.f('ix_pedido_proveedor_detalle_pedido'), table_name='pedido_proveedor_detalle')
    op.drop_index(op.f('ix_producto_unidad_medida_id'), table_name='producto')
    op.drop_index(op.f('ix_producto_unidad_unidad_medida_id'), table_name='producto_unidad')
    op.drop_index(op.f('ix_recepcion_proveedor_pedido'), table_name='recepcion_proveedor')
    op.drop_index(op.f('ix_recepcion_proveedor_proveedor'), table_name='recepcion_proveedor')
    op.drop_index(op.f('ix_recepcion_proveedor_sucursal'), table_name='recepcion_proveedor')
    op.drop_index(op.f('ix_recepcion_proveedor_detalle_recepcion'), table_name='recepcion_proveedor_detalle')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_recepcion_proveedor_detalle_recepcion'), 'recepcion_proveedor_detalle', ['recepcion_id'], unique=False)
    op.create_index(op.f('ix_recepcion_proveedor_sucursal'), 'recepcion_proveedor', ['sucursal_id'], unique=False)
    op.create_index(op.f('ix_recepcion_proveedor_proveedor'), 'recepcion_proveedor', ['proveedor_id'], unique=False)
    op.create_index(op.f('ix_recepcion_proveedor_pedido'), 'recepcion_proveedor', ['pedido_id'], unique=False)
    op.create_index(op.f('ix_producto_unidad_unidad_medida_id'), 'producto_unidad', ['unidad_medida_id'], unique=False)
    op.create_index(op.f('ix_producto_unidad_medida_id'), 'producto', ['unidad_medida_id'], unique=False)
    op.create_index(op.f('ix_pedido_proveedor_detalle_pedido'), 'pedido_proveedor_detalle', ['pedido_id'], unique=False)
    op.create_check_constraint(op.f('ck_pedido_proveedor_estado'), 'pedido_proveedor', "estado::text = ANY (ARRAY['borrador'::character varying, 'enviado'::character varying, 'confirmado'::character varying, 'parcial'::character varying, 'recibido'::character varying, 'cancelado'::character varying]::text[])")
    op.create_index(op.f('ix_pedido_proveedor_sucursal'), 'pedido_proveedor', ['sucursal_id'], unique=False)
    op.create_index(op.f('ix_pedido_proveedor_proveedor'), 'pedido_proveedor', ['proveedor_id'], unique=False)
    op.create_index(op.f('ix_movimiento_instancia_abierta'), 'movimiento_inventario', ['instancia_abierta_id'], unique=False)
    op.create_index(op.f('ix_devolucion_prov_detalle_recepcion_detalle'), 'devolucion_proveedor_detalle', ['recepcion_detalle_id'], unique=False)
    op.create_index(op.f('ix_devolucion_prov_detalle_devolucion'), 'devolucion_proveedor_detalle', ['devolucion_id'], unique=False)
    op.create_index(op.f('ix_devolucion_prov_recepcion'), 'devolucion_proveedor', ['recepcion_id'], unique=False)
    op.create_index(op.f('ix_devolucion_prov_proveedor'), 'devolucion_proveedor', ['proveedor_id'], unique=False)
    op.create_index(op.f('ix_devolucion_linea_devolucion'), 'devolucion_linea', ['devolucion_id'], unique=False)
    op.drop_index(op.f('ix_devolucion_venta_id'), table_name='devolucion')
    op.create_index(op.f('ix_devolucion_venta'), 'devolucion', ['venta_id'], unique=False)
    op.create_index(op.f('ix_devolucion_turno'), 'devolucion', ['caja_turno_id'], unique=False)
    op.create_index(op.f('ix_detalle_venta_cita'), 'detalle_venta', ['cita_id'], unique=False)
    op.create_index(op.f('ix_cita_sucursal'), 'cita', ['sucursal_id'], unique=False)
    op.create_index(op.f('ix_cita_empleado'), 'cita', ['empleado_id'], unique=False)
    op.create_index(op.f('uq_caja_turno_abierto_usuario'), 'caja_turno', ['usuario_id'], unique=True, postgresql_where="((estado)::text = 'abierto'::text)")
    op.create_index(op.f('uq_caja_turno_abierto_caja'), 'caja_turno', ['caja_id'], unique=True, postgresql_where="((estado)::text = 'abierto'::text)")
    # ### end Alembic commands ###
