"""Módulo de Auditoria, Eventos y Reportes

Revision ID: 6dbcded228a4
Revises: 1d5e34b811d5
Create Date: 2026-08-30 22:51:35.139587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dbcded228a4'
down_revision: Union[str, Sequence[str], None] = '1d5e34b811d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
