"""Módulo de Clientes y Ventas

Revision ID: 93b1b08ff9c7
Revises: e6f03f25243a
Create Date: 2026-08-30 22:25:46.648231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93b1b08ff9c7'
down_revision: Union[str, Sequence[str], None] = 'e6f03f25243a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
