"""Add clientes and ventas modules

Revision ID: e6f03f25243a
Revises: 4fbc43c86b78
Create Date: 2026-08-30 22:24:46.696350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6f03f25243a'
down_revision: Union[str, Sequence[str], None] = '4fbc43c86b78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sucursal_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('rfc_identificacion', sa.String(length=50), nullable=True),
    sa.Column('limite_credito', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('saldo_credito', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('caja_turno',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sucursal_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('saldo_inicial', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('abierto_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cerrado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venta',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sucursal_id', sa.UUID(), nullable=False),
    sa.Column('caja_turno_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('descuento_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['caja_turno_id'], ['caja_turno.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalle_venta',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('venta_id', sa.UUID(), nullable=False),
    sa.Column('producto_id', sa.UUID(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('descuento_linea', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('impuesto_tasa', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pago',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('venta_id', sa.UUID(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('metodo_pago', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pago')
    op.drop_table('detalle_venta')
    op.drop_table('venta')
    op.drop_table('caja_turno')
    op.drop_table('cliente')
    # ### end Alembic commands ###
